"""Ground truth data from client's ACTUAL material list (IVCC CETLA).

Source: IVCC CETLA Electrical Material List.pdf
Generated by JB Contracting Corporation

This is the REAL target we need to match.
"""

# =============================================================================
# CONDUIT (from routing/takeoff)
# =============================================================================

GROUND_TRUTH_CONDUIT = {
    '1/2" EMT': 100,
    '3/4" EMT': 3773,
    '1" EMT': 790,
    '1-1/4" EMT': 655,
}

# =============================================================================
# FIXTURES (from floor plans E200)
# =============================================================================

GROUND_TRUTH_FIXTURES = {
    "F2": 6,       # L.E.D. 2'x4' Lay-In
    "F3": 10,      # 4' L.E.D. Strip
    "F4": 10,      # L.E.D. Recessed Downlight
    "F4E": 2,      # L.E.D. Recessed Downlight (Emergency)
    "F5": 8,       # 4' Vapor Tite Fixture
    "F7": 3,       # 2'x4' Surface L.E.D. Fixture
    "F7E": 2,      # 2'x4' Surface L.E.D. Fixture (Emergency)
    "F8": 1,       # L.E.D. 2'x2' Lay-In
    "F9": 6,       # 6' Linear LED
    "X1": 5,       # Exit Fixture w/Batt Pack
    "X2": 1,       # Exit Fixture w/Batt Pack
}

# =============================================================================
# LINEAR LED FIXTURES (from E600 schedule)
# =============================================================================

GROUND_TRUTH_LINEAR = {
    "4' Linear LED": 16,
    "6' Linear LED": 12,
    "8' Linear LED": 8,
    "10' Linear LED": 14,
    "16' Linear LED": 2,
    "4' L.E.D. Strip": 4,  # Item "4 STRIP"
}

# =============================================================================
# PENDANT FIXTURES (from E600 schedule)
# =============================================================================

GROUND_TRUTH_PENDANTS = {
    "F10-22": 3,       # 22' Linear LED
    "F10-30": 2,       # 30' Linear LED
    "F11-4X4": 4,      # 4x4 Linear Pendant
    "F11-6X6": 3,      # 6x6 Linear Pendant
    "F11-8X8": 2,      # 8x8 Linear Pendant
    "F11-10X10": 3,    # 10x10 Linear Pendant (F1110X10 in list)
    "F11-16X10": 1,    # 16x10 Linear Pendant (F1116X10 in list)
}

# =============================================================================
# CONTROLS (from floor plans E200)
# =============================================================================

GROUND_TRUTH_CONTROLS = {
    "Ceiling Occupancy Sensor": 16,    # Dual Technology Ceiling Mount Sensor
    "Wall Occupancy Sensor": 3,        # 2 Button Dual Tech Wall Switch
    "Daylight Sensor": 3,              # Wireless Daylight Ceiling Mount Sensor
    "Wireless Dimmer": 10,             # Lutron Wireless Dimmer
    "Power Pack": 14,                  # Power Pack for Lighting Control Sensors
}

# =============================================================================
# POWER DEVICES (from floor plans E201)
# =============================================================================

GROUND_TRUTH_POWER = {
    "Duplex Receptacle": 37,    # 20A/125V Spec Grade Dup Rcpt (5-20R)
    "GFI Receptacle": 5,        # 20A/125V Spec Grade GFI (5-20R)
    "SP Switch": 3,             # 20A Spec Grade SP Switch
    "3-Way Switch": 2,          # 20A Spec Grade 3-Way Switch
}

# =============================================================================
# PANEL & BREAKERS (from E700 schedule)
# =============================================================================

GROUND_TRUTH_PANEL = {
    "20A 1P Breaker": 14,              # 20A 1P 120/240V Bolt-On Circuit Breaker
    "30A 2P Breaker": 1,               # 30A 2P 120/240V Bolt-On Circuit Breaker
    "30A/2P Safety Switch 240V": 1,    # 30A/2P 3WSN 240V HD Fus Safety Sw
    "30A/3P Safety Switch 600V": 1,    # 30A/3P 600V HD Fus Safety Sw
    "100A/3P Safety Switch 600V": 1,   # FDS-ELEV: 100A/3P 600V HD Fus Safety Sw
}

# =============================================================================
# DEMOLITION (from E100)
# =============================================================================

GROUND_TRUTH_DEMO = {
    "Demo 2'x4' Recessed": 7,
    "Demo 2'x2' Recessed": 12,
    "Demo Downlight": 12,        # Demo Recessed Down Lite
    "Demo 4' Strip": 1,
    "Demo 8' Strip": 27,
    "Demo Exit": 2,
    "Demo Receptacle": 13,       # Demo 20A Receptacle
    "Demo Floor Box": 23,
    "Demo Switch": 2,            # Demo Toggle Switch
}

# =============================================================================
# TECHNOLOGY (from T200)
# =============================================================================

GROUND_TRUTH_TECHNOLOGY = {
    "Cat 6 Jack": 92,
    "Cat 6 Cable (ft)": 920,     # Cat 6 Plenum (CMP) 23 Gauge 4-Pair Cable
    "J-Hook": 230,               # 4" Galvanized J Hook
}

# =============================================================================
# BOXES (derived from devices)
# =============================================================================

GROUND_TRUTH_BOXES = {
    '4" Square Box': 61,
    '4" Square Box w/bracket': 103,    # 4" Square x 1-1/2" Deep Box w/bkt
    '4" Square Box 2-1/8" deep': 10,   # 4" Square x 2-1/8" Deep Box w/brkt
    '4-11/16" Square Box': 14,
    '4-11/16" Square Box w/bracket': 89,
}

# =============================================================================
# PLASTER RINGS (derived from boxes)
# =============================================================================

GROUND_TRUTH_RINGS = {
    '4" Square-3/0 Plaster Ring': 61,  # 48 (1/2"D) + 13 (5/8"D)
    '4" Square-1G Plaster Ring': 67,
    '4" Square-2G Plaster Ring': 3,
    '4-11/16"-1G Plaster Ring': 89,
}

# =============================================================================
# COVER PLATES (derived from devices)
# =============================================================================

GROUND_TRUTH_PLATES = {
    "Decora Plate": 8,           # 1G Plastic Decora Plate
    "Duplex Plate": 34,          # 31 (1G) + 3 (2G)
    "Switch Plate": 5,           # 1G Plastic Switch Plate
    "Blank Cover": 13,           # 4" Square Flat Blank Cover
    "Blank Cover w/KO": 28,      # 14 (4") + 14 (4-11/16")
}

# =============================================================================
# FITTINGS (derived from conduit)
# =============================================================================

GROUND_TRUTH_FITTINGS = {
    # Connectors
    '1/2" Connector': 10,
    '3/4" Connector': 395,
    '1" Connector': 39,
    '1-1/4" Connector': 77,
    # Couplings
    '1/2" Coupling': 8,
    '3/4" Coupling': 348,
    '1" Coupling': 64,
    '1-1/4" Coupling': 38,
    # Bushings
    '1/2" Bushing': 10,
    '3/4" Bushing': 395,
    '1" Bushing': 39,
    '1-1/4" Bushing': 77,
    # Straps
    '1/2" 1-Hole Strap': 12,
    '3/4" 1-Hole Strap': 348,
    '1" 1-Hole Strap': 15,
    '1-1/4" 1-Hole Strap': 27,
    '3/4" Unistrut Strap': 116,
    '1" Unistrut Strap': 80,
    '1-1/4" Unistrut Strap': 48,
}

# =============================================================================
# WIRE (derived from conduit)
# =============================================================================

GROUND_TRUTH_WIRE = {
    "#12 THHN": 8548,
    "#10 THHN": 6625,
    "#8 THHN": 50,
    "#3 THHN": 150,
}

# =============================================================================
# CONSUMABLES
# =============================================================================

GROUND_TRUTH_CONSUMABLES = {
    "Red Wirenut": 660,          # Red Wirenuts (10-18 gauge)
    "Red Scotchlok": 36,         # Red Scotchlok Wirenuts (#18-10)
    "Ground Screw": 90,          # 39 (with pigtail) + 51 (plain)
    "Pan Head Screw": 360,       # 6X1/4" Pan Head Tapping Screw
    "Poly Pull Line (ft)": 1837,
}

# =============================================================================
# ACCESSORIES
# =============================================================================

GROUND_TRUTH_ACCESSORIES = {
    "Fixture Whip": 16,          # Manufactured Fixture Whip (14/3)
    "Pendant/Cable": 91,         # Pendant /Cable (length as required)
    "Seismic Wire": 6,
}

# =============================================================================
# COMBINED DICTIONARIES
# =============================================================================

# All counted items (from floor plans and schedules)
GROUND_TRUTH_COUNTED = {
    **GROUND_TRUTH_FIXTURES,
    **GROUND_TRUTH_LINEAR,
    **GROUND_TRUTH_PENDANTS,
    **GROUND_TRUTH_CONTROLS,
    **GROUND_TRUTH_POWER,
    **GROUND_TRUTH_PANEL,
    **GROUND_TRUTH_DEMO,
    **GROUND_TRUTH_TECHNOLOGY,
}

# All derived items (from business rules)
GROUND_TRUTH_DERIVED = {
    **GROUND_TRUTH_CONDUIT,
    **GROUND_TRUTH_FITTINGS,
    **GROUND_TRUTH_BOXES,
    **GROUND_TRUTH_RINGS,
    **GROUND_TRUTH_PLATES,
    **GROUND_TRUTH_WIRE,
    **GROUND_TRUTH_CONSUMABLES,
    **GROUND_TRUTH_ACCESSORIES,
}

# Everything combined
ALL_GROUND_TRUTH = {
    **GROUND_TRUTH_COUNTED,
    **GROUND_TRUTH_DERIVED,
}

# =============================================================================
# VALIDATION HELPERS
# =============================================================================

def get_category(item: str) -> str:
    """Determine the category of a material item."""
    if item in GROUND_TRUTH_FIXTURES:
        return "Fixtures"
    elif item in GROUND_TRUTH_LINEAR:
        return "Linear LEDs"
    elif item in GROUND_TRUTH_PENDANTS:
        return "Pendants"
    elif item in GROUND_TRUTH_CONTROLS:
        return "Controls"
    elif item in GROUND_TRUTH_POWER:
        return "Power"
    elif item in GROUND_TRUTH_PANEL:
        return "Panel"
    elif item in GROUND_TRUTH_DEMO:
        return "Demo"
    elif item in GROUND_TRUTH_TECHNOLOGY:
        return "Technology"
    elif item in GROUND_TRUTH_CONDUIT:
        return "Conduit"
    elif item in GROUND_TRUTH_FITTINGS:
        return "Fittings"
    elif item in GROUND_TRUTH_BOXES:
        return "Boxes"
    elif item in GROUND_TRUTH_RINGS:
        return "Rings"
    elif item in GROUND_TRUTH_PLATES:
        return "Plates"
    elif item in GROUND_TRUTH_WIRE:
        return "Wire"
    elif item in GROUND_TRUTH_CONSUMABLES:
        return "Consumables"
    elif item in GROUND_TRUTH_ACCESSORIES:
        return "Accessories"
    else:
        return "Unknown"


def get_item_count() -> int:
    """Get total number of unique items."""
    return len(ALL_GROUND_TRUTH)


def get_total_quantity() -> int:
    """Get total quantity across all items."""
    return sum(ALL_GROUND_TRUTH.values())


def print_summary():
    """Print a summary of ground truth data."""
    categories = {}
    for item, qty in ALL_GROUND_TRUTH.items():
        cat = get_category(item)
        if cat not in categories:
            categories[cat] = {"items": 0, "quantity": 0}
        categories[cat]["items"] += 1
        categories[cat]["quantity"] += qty

    print("=" * 60)
    print("GROUND TRUTH SUMMARY - IVCC CETLA (from client PDF)")
    print("=" * 60)
    print(f"{'Category':<20} {'Items':>10} {'Total Qty':>15}")
    print("-" * 60)

    for cat in sorted(categories.keys()):
        data = categories[cat]
        print(f"{cat:<20} {data['items']:>10} {data['quantity']:>15,}")

    print("-" * 60)
    print(f"{'TOTAL':<20} {get_item_count():>10} {get_total_quantity():>15,}")
    print("=" * 60)


if __name__ == "__main__":
    print_summary()
